version: '3.3'

services:
   db:
     env_file:
      - .env.example
     image: mysql:${MYSQL_VERSION}
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     env_file:
      - .env.example
     depends_on:
       - db
     image: wordpress:${WORDPRESS_VERSION}
     ports:
       - "${APP_PORT}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${WORDPRESS_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWORD}
       WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE}
volumes:
    db_data: {}